### ISSUE TITLE
Felix link color

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#11]
Change text links to teal: #07a6aa.
I know we talked about leaving them dark blue but they don't stand out enough.

**Comment by travishathaway** [comment]
@loreguerra I have fixed the link color.  You can check it out here:

https://stage.felixinstruments.com

**Comment by loreguerra** [comment]
Looks good. These need to remain dark blue links: 
![screen shot 2016-04-06 at 3 39 05 pm](https://cloud.githubusercontent.com/assets/16310498/14335115/cb3125a6-fc0d-11e5-99cc-a12bcc4c8e15.png)

**Comment by travishathaway** [comment]
Okay,

I will leave all links contained within H tags dark blue.
