### ISSUE TITLE
CID new logo on salesteam

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#15]
Please add the new logo .png file to the **salesteam** header

![cidsalesteamlogo](https://cloud.githubusercontent.com/assets/16310498/14616580/e1eafc62-055f-11e6-85ef-5ec00be312df.png)

**Comment by loreguerra** [comment]
Logo is attached above, but not visible. Was also sent to you in an email on March 8th.

**Comment by travishathaway** [comment]
@loreguerra 

This is fixed.  The logo you provided was already there though.  Maybe a browser cache issue?

**Comment by loreguerra** [comment]
Please apply the logo from the staging felix site to salesteam felix

**Comment by travishathaway** [comment]
@loreguerra 

Switched it over.  The changes are on the staging site.

**Comment by loreguerra** [comment]
Great. Thank you. Can you make it a tiny bit smaller so there are some margins?

<img width="460" alt="screen shot 2016-04-20 at 9 19 09 am" src="https://cloud.githubusercontent.com/assets/16310498/14682135/00055fd8-06d9-11e6-9c59-468178ae0979.png">

**Comment by travishathaway** [comment]
@loreguerra 

Made the image a bit smaller and added a 5px of maring to top and bottom.
