### ISSUE TITLE
Testimonial author formatting

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#20]
Should be "small-text" and #cccccc

<img width="328" alt="screen shot 2016-04-18 at 12 40 31 pm" src="https://cloud.githubusercontent.com/assets/16310498/14617375/cfa46540-0562-11e6-8bbd-14bc1eeea6a0.png">

**Comment by travishathaway** [comment]
@loreguerra 

Fixed it.  "cccccc" is pretty light though.  Let me know if you want me to change it.

**Comment by loreguerra** [comment]
You're right.#999999

**Comment by travishathaway** [comment]
@loreguerra 

Changed it to #999999. It's on staging.
