### ISSUE TITLE
404 page edits

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#24]
Please make the 404 page accessible and editable in Mezzanine.

**Comment by loreguerra** [comment]
Regarding your email, my edits are below:

404:
Title: 404 Page Not Found
Body: 
It appears we are unable to locate the content you are looking for. Please click here to return to the home page. If you have a support issue, click here (links to support page) or contact us here. (leads to contact page)

500:
Title: 500 Server Error
Body:
It appears something has gone wrong. Click here to return to the homepage.

Double check for spelling/missing words!

**Comment by travishathaway** [comment]
@loreguerra 

Updated everything.  Grammar is also good too.  It's up on staging right now.

**Comment by loreguerra** [comment]
Great. Thank you. Can you make it editable?

**Comment by travishathaway** [comment]
@loreguerra 

The 404 page is editable, but the 500 page is not.  The 404 will be the most common error any way so I don't think will be a problem going forward.

**Comment by loreguerra** [comment]
Thank you.
