### ISSUE TITLE
All products page buttons

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#26]
Have buttons bottom align like on the home page

<img width="906" alt="screen shot 2016-04-18 at 12 54 41 pm" src="https://cloud.githubusercontent.com/assets/16310498/14617864/c96fb2ea-0564-11e6-9b19-924084da9c95.png">

**Comment by travishathaway** [comment]
@loreguerra 

I have implemented a fix for this.  Now, each product has a "min-height" of 250px.  This works well with our current layout and is up on the staging server for you to view.

**Comment by loreguerra** [comment]
It's not quite working here. Is there another solution? 

https://stage.felixinstruments.com/food-science-instruments/portable-nir-analyzers/

<img width="449" alt="screen shot 2016-04-19 at 4 08 23 pm" src="https://cloud.githubusercontent.com/assets/16310498/14658523/21202cd8-0649-11e6-990c-094f4ed20c1f.png">

**Comment by travishathaway** [comment]
@loreguerra 

Thanks for catching that. I'll go back to drawing board.

**Comment by travishathaway** [comment]
@loreguerra 

I have implemented a fix for this. Everything should be good this time.

**Comment by loreguerra** [comment]
Looks great!
