### ISSUE TITLE
Home page graphic

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#29]
Attached is a zip file with html, an image and styles for how I want the home page image to look/function.

I’m fine with adding the text/styles into Mezzanine, but I just wanted you to see how I want to be able to add an image and set it to the size of 900px by 375px.

BUT I want to keep the TOUR HQ image functioning the same. So maybe it needs two galleries?

It’s attached, let me know if you have questions.

[homepageimage.zip](https://github.com/travishathaway/travazine/files/224685/homepageimage.zip)

**Comment by travishathaway** [comment]
@loreguerra 

I see what you're what saying, but unfortunately this layout only works at the largest screen resolutions.

If I was you, I would utilize the "hidden-sm", "hidden-xs" to come up with several variants for various screen sizes.  This way, you can use fixed widths without paying any penalty.  Keep in mind though that the smallest resolution (mobile), is completely fluid (you cannot use fixed width there). If you do it this way, we can leave the "Tour HQ" section untouched.

I put the code you sent over in place on the staging site.  As you can see, it does not scale down very well.

**Comment by loreguerra** [comment]
If I upload the image at 900x375 will it show up correctly?

If I give you a separate image for mobile, can you create the other responsive layouts with responsive text?

**Comment by loreguerra** [comment]
This got a little goofy with the home page graphic updates. Should be TOUR HQ

<img width="614" alt="screen shot 2016-04-19 at 3 51 04 pm 1" src="https://cloud.githubusercontent.com/assets/16310498/14658137/9ef98b84-0646-11e6-905b-1eb212e814b6.png">

**Comment by travishathaway** [comment]
@loreguerra 

I just now fixed that.  It's up on staging.

**Comment by loreguerra** [comment]
Great. I'll keep holding for the ability to edit the source code. Without that, I can't edit the font sizes.

**Comment by travishathaway** [comment]
@loreguerra 

I have disabled the code mirror editor and reverted to the default TinyMCE editor.  You should be able to make edits to HTML now.

**Comment by loreguerra** [comment]
PERFECT! Thank you
