### ISSUE TITLE
Incentives referral embedded form

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#31]
Will need to be created for Felix as well. Same functionality, appropriate email address, thank you page.

**Comment by travishathaway** [comment]
@loreguerra 

I have created this form on the old server:
https://cid-bioscience.com/felix_referrals/request_form.php

When you embed that, it will appropriately redirect you to https://felixinstruments.com/thank-you

**Comment by loreguerra** [comment]
I'm getting this message again when I try and access the HTML editor to embed the form.

I hope this wont' be an issue when the site launches since I'll have to make quick updates.

<img width="493" alt="screen shot 2016-04-19 at 12 57 07 pm" src="https://cloud.githubusercontent.com/assets/16310498/14653580/6ef16000-062e-11e6-8495-51c64e1c5bb0.png">

Also, the thank-you page leads to a "connection is not private" page.

**Comment by travishathaway** [comment]
@loreguerra 

I am having a difficult time recreating your issue with accessing the html editor.  Can you give it another try now?

Regarding the redirect on the form, the url "https://felixinstruments.com/thank-you" is hard coded in the html of those forms.  Right now that redirect is broken because the page does not exist yet, but when we launch the new Felix Instruments site, it will be there.  Everything will function just as it is on cid-inc.com right now.

**Comment by loreguerra** [comment]
Yes. I just tried and I'm still getting the error.

**Comment by loreguerra** [comment]
I embedded the form and when I submit, it just goes blank. Give it a try: https://stage.felixinstruments.com/referrals/

**Comment by JudithEdwards** [comment]
This also should have the same "Industry Sector" drop down as the Request pricing form instead of the "Select All Fields that Apply."

**Comment by loreguerra** [comment]
Added in Filemaker, just need Travis to add to the Referrals form.

**Comment by travishathaway** [comment]
@loreguerra and @JudithEdwards 

Changes made.  "Field of Study" is now "Industry Sector" on the referral form.  If you test it on staging for Felix, you will notice that it redirects you to "https://felixinstruments.com/thank-you.  This page does not currently exist, but when we launch the Felix it will exist; therefore, this will not be an issue.

Please let me know if you find anything thing else wrong with this form.

**Comment by loreguerra** [comment]
Great. Thank. 

Just to be sure, I don't have to create that thank-you page, do I?

**Comment by travishathaway** [comment]
@loreguerra 

It already exists, so no.  We should be good to go on this issue.
