### ISSUE TITLE
Applications dropdown needs to be "commodity"

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#32]
List of commodities have been sent to you.

> Just a heads up and for your reference, for Felix apps, we’ll be ditching the Field of Study dropdown and doing “Commodity”.
> 
> Here are the values so far for commodity.
> 
> Apple
> Fish
> Melon
> Lettuce
> Grapes/Wine
> Pears
> Edible Flowers

**Comment by travishathaway** [comment]
@loreguerra 

I have changed this on the Felix site to display as "Commodities" instead.  Internally it will still be known as "Field of Study" though (e.g. when you go to enter them on the admin pages).  It is currently up on the staging site if you want to check it out.

You can add these as yourself as you go about tagging publications. embedded content, and infographics.

**Comment by loreguerra** [comment]
Perfect.
