### ISSUE TITLE
Show appropriate products on Request Quote forms

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#34]
Show only CID products on CID form

Show Felix and Hanna on Felix form.

**Comment by travishathaway** [comment]
@loreguerra 

I have implemented a fix for this.  Please check it out on the staging site.

**Comment by loreguerra** [comment]
Looks like it works, but please have the original form field identifier:
<img width="484" alt="screen shot 2016-04-18 at 3 06 34 pm" src="https://cloud.githubusercontent.com/assets/16310498/14621399/56c1958e-0577-11e6-8a51-d81b642ba9f3.png">

**Comment by travishathaway** [comment]
@loreguerra 

Not sure I know what you mean? Can you clarify?

**Comment by loreguerra** [comment]
The form title should be "Instrument (pick all that apply)" as it was before.

You changed it to "instrument".

**Comment by AndreaM** [comment]
Travis, you changed the CID site, which was correct "Instrument (pick all that apply)" to "instrument"

Lorena was clear that BOTH sites need to list this dropdown as "Instrument (pick all that apply)". 
I don't know how this happened, but the CID site dropdown should absolutely not have changed. Please fix the CID site ASAP and make sure this gets implemented on both.

**Comment by travishathaway** [comment]
@AndreaM and @loreguerra 

Production site has been updated.  The appropriate labeling will also be present on the Felix site.
