### ISSUE TITLE
Make webinar attachments visible and accessible on detail pages

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#36]
Webinar attachments are only visible before you click on the application detail page

<img width="595" alt="screen shot 2016-04-18 at 4 04 34 pm" src="https://cloud.githubusercontent.com/assets/16310498/14622538/6b1aebcc-057f-11e6-8bf0-dfb92512ca3a.png">
<img width="757" alt="screen shot 2016-04-18 at 4 04 38 pm" src="https://cloud.githubusercontent.com/assets/16310498/14622539/6bfb6f76-057f-11e6-84cb-318215faa750.png">

**Comment by travishathaway** [comment]
@loreguerra 

This is fixed.  Attachments will now show just underneath the title.  It is up on staging.

**Comment by loreguerra** [comment]
But now it's underneath everything on the preview page. Can you make both have the same ordering of information?

**Comment by travishathaway** [comment]
@loreguerra 

The attachment now shows below everything just like on the list view.
