### ISSUE TITLE
Applications detail pages

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#37]
Have all applications (publications, embedded content and infographics) use the same application detail page template.

Display the product photo and name to the left of the content. Make sure the big gray title for each changes.

<img width="969" alt="screen shot 2016-04-18 at 4 07 17 pm" src="https://cloud.githubusercontent.com/assets/16310498/14622577/b12ae1e4-057f-11e6-9d68-8bd559bdd3cc.png">

**Comment by travishathaway** [comment]
@loreguerra 

This has been implemented for inforgraphics and embedded content (videos, webinars).  You can see it right on staging.

**Comment by loreguerra** [comment]
I see it on Felix and it looks great. Can you implement on CID staging so we can be sure everything looks ok?

**Comment by loreguerra** [comment]
Please have the video show up first, then the date, then attachments, then description text. Just like on the search page, before you click on video details.

Also, set the limit of the description text to 4-5 lines.

**Comment by loreguerra** [comment]
Please set the infographic to display up 650px wide in the viewing area.

The hierarchy here needs to match the rest of the apps:

<img width="425" alt="screen shot 2016-04-19 at 9 03 10 am" src="https://cloud.githubusercontent.com/assets/16310498/14646396/305d2812-060e-11e6-8968-e231aa2a3075.png">

<img width="426" alt="screen shot 2016-04-19 at 9 03 06 am" src="https://cloud.githubusercontent.com/assets/16310498/14646419/40b092da-060e-11e6-8145-6ffe03033d4f.png">

**Comment by travishathaway** [comment]
@loreguerra 

I have implement the fixes discussed in Skype (change the title to Helvetica Bold for infographic list view).  Consider this to be fixed.

**Comment by loreguerra** [comment]
Looks great. Please make sure the associated product thumbnails on CID staging get pushed live.
