### ISSUE TITLE
URL for embedded content

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#38]
<img width="474" alt="screen shot 2016-04-18 at 4 16 15 pm" src="https://cloud.githubusercontent.com/assets/16310498/14622723/ed28d7cc-0580-11e6-9672-b59e0ffc7b55.png">

Let's have it be cid-inc.com/webinars/webinar-name
same with videos: cid-inc.com/videos/video-name

**Comment by travishathaway** [comment]
@loreguerra 

I have the proper adjustments.  You can look at it right now on staging.  There currently are no videos up, but I have tested it locally, and it works as expected.

**Comment by loreguerra** [comment]
Great. Please implement into Felix as well.
