### ISSUE TITLE
Request Pricing form on Felix site

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#39]
I have created a new form field called "industry_sector" in FileMaker.

Can you please create this form field on the Felix request pricing form as a "pick all that apply" dropdown?

Everything associated with the field is called "industry_sector"

> Instead of Field of Study, it should be "Industry Sector" and have these options in the drop down:
> 
> Academic Researcher
> Grower
> Packer/Distributor
> Importer
> Retailer
> Equipment Reseller
> 
> These just get dropped into a note in the database, they don't go into a particular field. FYI.

**Comment by travishathaway** [comment]
@loreguerra 

This has been implemented.  You can see right on staging.  Can you please test out the form to make sure everything is being submitted? I made sure we're not error out on form submission.

**Comment by loreguerra** [comment]
The field is there. I tested the form and it sends to Judith, but does not populate "industry_sector".

**Comment by loreguerra** [comment]
Now industry_sector will log int FileMaker, but the options are listed as a string instead of a separated list. Charlie says you can created the list by using code similar to this: 

<img width="1558" alt="screen shot 2016-04-20 at 11 15 01 am" src="https://cloud.githubusercontent.com/assets/16310498/14685869/4172aaae-06eb-11e6-827f-74c16fc41fe5.png">

**Comment by travishathaway** [comment]
@loreguerra 

Thanks for the input! That was very helpful.  I believe I have addressed the issue.  Can you please try again, and verify whether this field is being appropriately populated in File Maker?

**Comment by loreguerra** [comment]
It's working correctly.
