### ISSUE TITLE
Applications page

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#44]
Please add the option to add an image to the sidebar under the Filtering section.

Should be fixed width and height: 220x220 and can be hidden for smaller layouts.

**Comment by travishathaway** [comment]
@loreguerra 

I've added a scribble that will allow you place an image in the right side bar.  I have loaded it with a default image from placehold.it.  I you have a better default image to use, that would good.

**Comment by loreguerra** [comment]
Perfect. Thank you
