### ISSUE TITLE
Breadcrumbs for Applications

### ISSUE THREAD

**Issue by loreguerra** [travishathaway/travazine#48]
If you click applications > publications > publication title there are no breadcrumbs visible.

This applies for all application types and on BOTH CID and Felix.

**Comment by travishathaway** [comment]
@loreguerra 

I have added bread crumbs to the application pages.

In the breadcrumbs, you see "Applications / Home".  When you are on a video and you click "Applications" it will take you back to the video section of the Applications page.  Please let me know if this is the kind of behavior you want.

it is up on staging right now.

**Comment by loreguerra** [comment]
Is there a way to do Home > Applications > Videos in the breadcrumbs?

**Comment by travishathaway** [comment]
@loreguerra 

Yes, I will add it in there.

**Comment by travishathaway** [comment]
@loreguerra 

It's up on staging now.
